<?php

return [
    'stage_policies' => [
        'chapter_planning' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => [], 'non_terminal_codes' => ['novel_paused']],
        'scene_generation' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => ['schema', 'evidence', 'length'], 'non_terminal_codes' => ['novel_paused', 'previous_scene_incomplete']],
        'chapter_assembly' => ['max_attempts' => 2, 'backoff' => [10], 'repairs' => ['length'], 'non_terminal_codes' => ['novel_paused', 'assembly_input_incomplete', 'assembly_scene_incomplete', 'assembly_context_incomplete']],
        'event_extraction' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => ['evidence'], 'non_terminal_codes' => ['novel_paused']],
        'review' => ['max_attempts' => 2, 'backoff' => [10], 'repairs' => [], 'non_terminal_codes' => ['novel_paused', 'review_prerequisite_missing']],
        // Rewrite 有 initial/retry/final 三档技术预算，Queue 必须允许三次投递才能真正到达最终档。
        'rewrite' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => ['evidence', 'length'], 'non_terminal_codes' => ['novel_paused', 'rewrite_exhausted']],
        'commit' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => []],
        'memory_summary' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => []],
        'embedding' => ['max_attempts' => 3, 'backoff' => [10, 30], 'repairs' => []],
        'ending_audit' => ['max_attempts' => 2, 'backoff' => [10], 'repairs' => []],
    ],
    'acceptance_tools_enabled' => (bool) env('GENERATION_ACCEPTANCE_TOOLS_ENABLED', false),
    'stalled_run_after_seconds' => (int) env('STALLED_RUN_AFTER_SECONDS', 480),
    'pending_job_seconds' => (int) env('GENERATION_PENDING_JOB_SECONDS', 900),
    'planner_max_output_tokens' => (int) env('PLANNER_MAX_OUTPUT_TOKENS', 12_000),
    'planner_retry_max_output_tokens' => (int) env('PLANNER_RETRY_MAX_OUTPUT_TOKENS', 16_000),
    'planner_final_retry_max_output_tokens' => (int) env('PLANNER_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000),
    'outline_request_budgets' => [
        'outline_foundation' => [
            'output_tokens' => (int) env('OUTLINE_FOUNDATION_OUTPUT_TOKENS', 8_000),
            'reasoning_reserve_tokens' => (int) env('OUTLINE_FOUNDATION_REASONING_RESERVE_TOKENS', 4_000),
        ],
        'outline_structure' => [
            'output_tokens' => (int) env('OUTLINE_STRUCTURE_OUTPUT_TOKENS', 12_000),
            'reasoning_reserve_tokens' => (int) env('OUTLINE_STRUCTURE_REASONING_RESERVE_TOKENS', 4_000),
        ],
        'outline_arc_beats' => [
            'output_tokens' => (int) env('OUTLINE_ARC_BEATS_OUTPUT_TOKENS', 8_000),
            'reasoning_reserve_tokens' => (int) env('OUTLINE_ARC_BEATS_REASONING_RESERVE_TOKENS', 4_000),
        ],
        'outline_beat_detail' => [
            'output_tokens' => (int) env('OUTLINE_BEAT_DETAIL_OUTPUT_TOKENS', 5_000),
            'reasoning_reserve_tokens' => (int) env('OUTLINE_BEAT_DETAIL_REASONING_RESERVE_TOKENS', 3_000),
        ],
    ],
    'scene_context_token_budget' => (int) env('SCENE_CONTEXT_TOKEN_BUDGET', 12_000),
    'scene_max_output_tokens' => (int) env('SCENE_MAX_OUTPUT_TOKENS', 12_000),
    'scene_retry_max_output_tokens' => (int) env('SCENE_RETRY_MAX_OUTPUT_TOKENS', 16_000),
    'scene_final_retry_max_output_tokens' => (int) env('SCENE_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000),
    'scene_length_repair_max_output_tokens' => (int) env('SCENE_LENGTH_REPAIR_MAX_OUTPUT_TOKENS', 4_000),
    'scene_job_soft_timeout_seconds' => (int) env('SCENE_JOB_SOFT_TIMEOUT_SECONDS', 300),
    'scene_job_safety_margin_seconds' => (int) env('SCENE_JOB_SAFETY_MARGIN_SECONDS', 20),
    'max_length_repair_attempts' => 1,
    'max_rewrite_length_repair_attempts' => 2,
    'max_coverage_repair_attempts' => 2,
    'coverage_repair_max_output_tokens' => 1_000,
    'coverage_repair_retry_max_output_tokens' => 2_000,
    'max_scene_structure_repair_attempts' => 2,
    'scene_structure_repair_max_output_tokens' => 1_000,
    'scene_structure_repair_retry_max_output_tokens' => 2_000,
    'previous_scene_tail_characters' => (int) env('PREVIOUS_SCENE_TAIL_CHARACTERS', 1_000),
    'chapter_min_length_ratio' => .85,
    'chapter_max_length_ratio' => 1.15,
    'event_extraction_max_output_tokens' => (int) env('EVENT_EXTRACTION_MAX_OUTPUT_TOKENS', 4_000),
    'event_extraction_retry_max_output_tokens' => (int) env('EVENT_EXTRACTION_RETRY_MAX_OUTPUT_TOKENS', 8_000),
    'event_extraction_final_retry_max_output_tokens' => (int) env('EVENT_EXTRACTION_FINAL_RETRY_MAX_OUTPUT_TOKENS', 12_000),
    'max_event_evidence_repair_attempts' => 2,
    'event_evidence_repair_max_output_tokens' => 1_000,
    'event_evidence_repair_retry_max_output_tokens' => 4_000,
    'review_max_output_tokens' => (int) env('REVIEW_MAX_OUTPUT_TOKENS', 12_000),
    'review_context_token_budget' => (int) env('REVIEW_CONTEXT_TOKEN_BUDGET', 32_000),
    'review_schema_repair_max_output_tokens' => 1_500,
    'coverage_judgment_repair_max_output_tokens' => 1_500,
    'review_pass_score' => (float) env('REVIEW_PASS_SCORE', 80),
    'rewrite_max_output_tokens' => (int) env('REWRITE_MAX_OUTPUT_TOKENS', 16_000),
    'rewrite_retry_max_output_tokens' => (int) env('REWRITE_RETRY_MAX_OUTPUT_TOKENS', 20_000),
    'rewrite_final_retry_max_output_tokens' => (int) env('REWRITE_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000),
    'max_rewrite_attempts' => (int) env('MAX_REWRITE_ATTEMPTS', 2),
    'summary_max_output_tokens' => (int) env('SUMMARY_MAX_OUTPUT_TOKENS', 1_200),
    'summary_retry_max_output_tokens' => (int) env('SUMMARY_RETRY_MAX_OUTPUT_TOKENS', 2_400),
    'summary_final_retry_max_output_tokens' => (int) env('SUMMARY_FINAL_RETRY_MAX_OUTPUT_TOKENS', 4_000),
    // Chapter Pipeline 将可见输出与推理预留分开冻结；旧 max_output 配置继续表示可见输出额度。
    'chapter_request_budgets' => [
        'planner' => [
            'initial' => ['output_tokens' => (int) env('PLANNER_MAX_OUTPUT_TOKENS', 12_000), 'reasoning_reserve_tokens' => (int) env('PLANNER_REASONING_RESERVE_TOKENS', 0)],
            'retry' => ['output_tokens' => (int) env('PLANNER_RETRY_MAX_OUTPUT_TOKENS', 16_000), 'reasoning_reserve_tokens' => (int) env('PLANNER_RETRY_REASONING_RESERVE_TOKENS', env('PLANNER_REASONING_RESERVE_TOKENS', 0))],
            'final' => ['output_tokens' => (int) env('PLANNER_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000), 'reasoning_reserve_tokens' => (int) env('PLANNER_FINAL_RETRY_REASONING_RESERVE_TOKENS', env('PLANNER_RETRY_REASONING_RESERVE_TOKENS', env('PLANNER_REASONING_RESERVE_TOKENS', 0)))],
        ],
        'writer' => [
            'initial' => ['output_tokens' => (int) env('SCENE_MAX_OUTPUT_TOKENS', 12_000), 'reasoning_reserve_tokens' => (int) env('SCENE_REASONING_RESERVE_TOKENS', 0)],
            'retry' => ['output_tokens' => (int) env('SCENE_RETRY_MAX_OUTPUT_TOKENS', 16_000), 'reasoning_reserve_tokens' => (int) env('SCENE_RETRY_REASONING_RESERVE_TOKENS', env('SCENE_REASONING_RESERVE_TOKENS', 0))],
            'final' => ['output_tokens' => (int) env('SCENE_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000), 'reasoning_reserve_tokens' => (int) env('SCENE_FINAL_RETRY_REASONING_RESERVE_TOKENS', env('SCENE_RETRY_REASONING_RESERVE_TOKENS', env('SCENE_REASONING_RESERVE_TOKENS', 0)))],
        ],
        'extractor' => [
            // DeepSeek 已出现 4,000 Token 全部用于隐藏推理的真实响应；三档递增预留让推理耗尽可以安全升级，而不是原参数重试。
            'initial' => ['output_tokens' => (int) env('EVENT_EXTRACTION_MAX_OUTPUT_TOKENS', 4_000), 'reasoning_reserve_tokens' => (int) env('EVENT_EXTRACTION_REASONING_RESERVE_TOKENS', 8_000)],
            'retry' => ['output_tokens' => (int) env('EVENT_EXTRACTION_RETRY_MAX_OUTPUT_TOKENS', 8_000), 'reasoning_reserve_tokens' => (int) env('EVENT_EXTRACTION_RETRY_REASONING_RESERVE_TOKENS', 16_000)],
            'final' => ['output_tokens' => (int) env('EVENT_EXTRACTION_FINAL_RETRY_MAX_OUTPUT_TOKENS', 12_000), 'reasoning_reserve_tokens' => (int) env('EVENT_EXTRACTION_FINAL_RETRY_REASONING_RESERVE_TOKENS', 24_000)],
        ],
        'reviewer' => [
            'initial' => ['output_tokens' => (int) env('REVIEW_MAX_OUTPUT_TOKENS', 12_000), 'reasoning_reserve_tokens' => (int) env('REVIEW_REASONING_RESERVE_TOKENS', 0)],
        ],
        'rewrite' => [
            'initial' => ['output_tokens' => (int) env('REWRITE_MAX_OUTPUT_TOKENS', 16_000), 'reasoning_reserve_tokens' => (int) env('REWRITE_REASONING_RESERVE_TOKENS', 0)],
            'retry' => ['output_tokens' => (int) env('REWRITE_RETRY_MAX_OUTPUT_TOKENS', 20_000), 'reasoning_reserve_tokens' => (int) env('REWRITE_RETRY_REASONING_RESERVE_TOKENS', env('REWRITE_REASONING_RESERVE_TOKENS', 0))],
            'final' => ['output_tokens' => (int) env('REWRITE_FINAL_RETRY_MAX_OUTPUT_TOKENS', 24_000), 'reasoning_reserve_tokens' => (int) env('REWRITE_FINAL_RETRY_REASONING_RESERVE_TOKENS', env('REWRITE_RETRY_REASONING_RESERVE_TOKENS', env('REWRITE_REASONING_RESERVE_TOKENS', 0)))],
        ],
        'summary' => [
            'initial' => ['output_tokens' => (int) env('SUMMARY_MAX_OUTPUT_TOKENS', 1_200), 'reasoning_reserve_tokens' => (int) env('SUMMARY_REASONING_RESERVE_TOKENS', 0)],
            'retry' => ['output_tokens' => (int) env('SUMMARY_RETRY_MAX_OUTPUT_TOKENS', 2_400), 'reasoning_reserve_tokens' => (int) env('SUMMARY_RETRY_REASONING_RESERVE_TOKENS', env('SUMMARY_REASONING_RESERVE_TOKENS', 0))],
            'final' => ['output_tokens' => (int) env('SUMMARY_FINAL_RETRY_MAX_OUTPUT_TOKENS', 4_000), 'reasoning_reserve_tokens' => (int) env('SUMMARY_FINAL_RETRY_REASONING_RESERVE_TOKENS', env('SUMMARY_RETRY_REASONING_RESERVE_TOKENS', env('SUMMARY_REASONING_RESERVE_TOKENS', 0)))],
        ],
    ],
];
